grails-app/views/project/csProjectTemplate.gsp
web-app/js/projectActivity.js
web-app/js/projects.js

This change requires PR AtlasOfLivingAustralia/ecodata#132 from Ecodata.

Biocollect 96

---

grails-app/taglib/au/org/ala/biocollect/merit/FCTagLib.groovy
grails-app/views/comment/_comment.gsp
web-app/css/comment.css

changed css class name due to conflict

code review comment change

---

grails-app/i18n/messages.properties
grails-app/views/project/create.gsp
web-app/js/projects.js

This change requires a new value in the external properties file: termsOfUseUrl -> full URL of the page with the terms of use.

biocollect-13 Add terms of use to project metadata

---

grails-app/conf/ApplicationResources.groovy
grails-app/views/projectActivity/_list.gsp
web-app/css/surveys.css
web-app/js/projectActivity.js

removed progress bar
right aligned survey status

#267: modified surveys page responsive with a fixed survey logo

---

grails-app/views/project/_dayscountTile.gsp
grails-app/views/project/citizenScience.gsp
grails-app/views/project/ecoScience.gsp
grails-app/views/shared/_projectFinder.gsp
grails-app/views/shared/_projectFinderQueryPanel.gsp
grails-app/views/shared/_projectFinderResultPanelTile.gsp
grails-app/views/shared/_projectFinderResultSummary.gsp
web-app/css/project-finder.css
web-app/css/project-tile-view.css
web-app/js/project-finder.js
web-app/js/projects.js

#541 & #542 feedback

---

grails-app/taglib/au/org/ala/biocollect/ModelTagLib.groovy

Allow delete row buttons to be turned off for tabular entries with pre-filled rows. Eg. The Great Victorian Fish Count has a table of common species.
To prevent delete icons, add "allowRowDelete": false, to the dataModel entry in dataModel.json supplied by the ecodata server.

Fix for https://github.com/AtlasOfLivingAustralia/biocollect/issues/696

---

web-app/js/projectActivities.js
web-app/js/projectActivity.js

- Subscribe to pActivityFormName only for the currently displayed projectActivity

#603 - Fixing test issues

---

grails-app/views/shared/_attachDocument.gsp
web-app/js/document.js

AtlasOfLivingAustralia/biocollect#885 cannot upload project resources.

---

grails-app/assets/javascripts/chartjsManager.js
grails-app/assets/javascripts/knockout-custom-bindings.js
grails-app/i18n/messages.properties
grails-app/views/shared/_chartGraphTab.gsp
grails-app/views/shared/_jsonEditorModal.gsp
src/test/js/spec/ChartjsManagerSpec.js

Allow setting chartjs font.
Fixed some typos and bugs in chartjs config building.
Additional tests.
Closes #1323

Allow changing main axis labels, fixed issues creating chartjs settings.

---

build.gradle
grails-app/conf/application.yml
grails-app/controllers/au/org/ala/biocollect/BioActivityController.groovy
grails-app/controllers/au/org/ala/biocollect/DocumentController.groovy
grails-app/services/au/org/ala/biocollect/merit/WebService.groovy
src/test/groovy/au/org/ala/biocollect/DocumentControllerSpec.groovy
src/test/groovy/au/org/ala/biocollect/merit/WebServiceSpec.groovy

add host name to relative document url path
fixed map not showing on data tab issue

fixes #1396 & #1397

---

grails-app/assets/javascripts/knockout-custom-bindings.js
grails-app/assets/javascripts/knockout-dates.js

The console log of changes to a project (via knockout.js change tracking) helps to know what has changed and debug any issues with saving project data.
Also adds a simple knockout debug handler to ease development.

Add a console log of project data changes.

---

grails-app/assets/javascripts/forms-manifest.js
grails-app/i18n/messages.properties
grails-app/services/au/org/ala/biocollect/merit/FormSpeciesFieldParserService.groovy
grails-app/services/au/org/ala/biocollect/merit/SpeciesService.groovy
grails-app/views/bulkImport/_adminActions.gsp
grails-app/views/bulkImport/index.gsp
grails-app/views/bulkImport/listings.gsp
grails-app/views/shared/_pagination.gsp

https://github.com/AtlasOfLivingAustralia/biocollect/issues/1242 
- fixes download of table template on a form
https://github.com/AtlasOfLivingAustralia/biocollect/issues/1506
- fixes species config not showing for repeat sections
https://github.com/AtlasOfLivingAustralia/biocollect/issues/1514
- fixes null text appearing for unmatched taxon
https://github.com/AtlasOfLivingAustralia/biocollect/issues/1465 
- removing ability to get to the last page. ES does not support this capability for large datasets.

Feature/fixes 6.5

---

gradle.properties
grails-app/controllers/au/org/ala/biocollect/BioActivityController.groovy
grails-app/views/layouts/mobile.gsp
src/test/groovy/au/org/ala/biocollect/BioActivityControllerSpec.groovy

do not encode user name and other user credentials on pages used by mobile

do not encode credentials

---

build.gradle
gradle.properties

using ecodata-client-plugin:6.1.1-SNAPSHOT

6.6.4-SNAPSHOT

---

gradle.properties
grails-app/assets/javascripts/i18n.js
grails-app/assets/javascripts/knockout-custom-bindings.js
grails-app/controllers/au/org/ala/biocollect/merit/HomeController.groovy
grails-app/services/au/org/ala/biocollect/merit/CommonService.groovy

added async internationalisation ko binding

---

forms/hub/friendsGrassTreeHealth/friendsGrassTreeHealthSurvey.json

Hi @temi for your review is the initial draft survey form for Friends Grasstree Health.
https://biocollect-test.ala.org.au/acsa/bioActivity/create/306674a3-00d8-4192-8336-f87bec71b837

commit Friends Grass Tree Health Survey #1626

---

grails-app/assets/javascripts/enterBioActivityData.js

- fixed bug with bulk import showing imported activity as errored.

#1684 fixed bug with bulk import showing imported activity as errored.

---

grails-app/controllers/au/org/ala/biocollect/merit/SiteController.groovy

- fixes creation of reusable site from survey form

#1734 - fixes creation of reusable site from survey form

---

grails-app/i18n/messages.properties
grails-app/views/shared/_facetView.gsp

- renamed facet choose more to more options and it is alway visible to exclude

#1752 renamed facet choose more to more options and it is alway visible to exclude

---

grails-app/assets/javascripts/activity.js
grails-app/assets/javascripts/common-bs4.js
grails-app/assets/javascripts/enterActivityData.js
grails-app/assets/javascripts/enterBioActivityData.js
grails-app/assets/javascripts/fieldcapture-application.js
grails-app/assets/javascripts/outputs.js
grails-app/assets/javascripts/projects.js

- fixes amplify exception stopping save operation from executing

#1229 fixes amplify exception stopping save operation from executing
